import { Link } from "@tanstack/react-router";
import { useState, type ReactNode } from "react";
import { Menu, X, ArrowUpRight } from "lucide-react";
import { Button } from "@/components/ui/button";

export function Mark({ descriptor }: { descriptor?: string | undefined }) {
  return <span className="inline-flex items-center gap-3"><svg viewBox="0 0 42 42" className="h-9 w-9 shrink-0" role="img" aria-label="FrontDesk monogram"><rect x="1" y="1" width="40" height="40" rx="5" className="fill-brand-ink"/><path d="M10 31V11h13M10 20h10M25 11h3c7 0 10 4 10 10s-3 10-10 10h-7V18" fill="none" stroke="white" strokeWidth="3.5" strokeLinecap="square"/><path d="M24 24c2 3 5 4 8 2" fill="none" className="stroke-brand" strokeWidth="3" strokeLinecap="round"/></svg><span className="flex flex-col leading-none"><strong className="font-display text-base font-extrabold">FRONTDESK</strong>{descriptor && <span className="mt-1 text-[10px] font-bold tracking-[0.14em] text-brand">{descriptor}</span>}</span></span>;
}
const nav = [{ label: "Dental", to: "/dental" }, { label: "Trades", to: "/trades" }, { label: "How it works", to: "/how-it-works" }, { label: "Pricing", to: "/pricing" }, { label: "Demo", to: "/demo" }] as const;
export function Marketing({ children, descriptor }: { children: ReactNode; descriptor?: string | undefined }) {
  const [open, setOpen] = useState(false);
  return <div className="min-h-screen bg-background text-foreground"><header className="sticky top-0 z-50 border-b border-border bg-background/95 backdrop-blur"><div className="mx-auto flex h-17 max-w-7xl items-center justify-between gap-5 px-5 sm:px-8"><Link to="/" aria-label="FrontDesk home" onClick={() => setOpen(false)}><Mark descriptor={descriptor}/></Link><nav className="hidden items-center gap-7 text-sm font-semibold lg:flex"><span className="text-muted-foreground">Solutions</span>{nav.map(n => <Link key={n.to} to={n.to} activeProps={{ className: "text-brand" }} className="hover:text-brand">{n.label}</Link>)}</nav><div className="hidden lg:flex"><Button asChild><Link to="/demo">Hear a Demo <ArrowUpRight /></Link></Button></div><Button variant="ghost" size="icon" aria-label={open ? "Close menu" : "Open menu"} aria-expanded={open} className="lg:hidden" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</Button></div>{open && <nav className="border-t border-border bg-background px-5 py-4 lg:hidden"><p className="mb-2 text-xs font-bold uppercase text-muted-foreground">Solutions</p>{nav.map(n => <Link key={n.to} to={n.to} onClick={() => setOpen(false)} className="block border-b border-border py-3 text-sm font-semibold">{n.label}</Link>)}<Button asChild className="mt-4 w-full"><Link to="/demo" onClick={() => setOpen(false)}>Hear a Demo</Link></Button></nav>}</header><main>{children}</main><footer className="border-t border-border bg-muted/40"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-5 py-10 sm:flex-row sm:items-end sm:justify-between sm:px-8"><div><Link to="/"><Mark /></Link><p className="mt-4 max-w-sm text-sm text-muted-foreground">AI call handling for UK service businesses. Dental and trades.</p></div><div className="flex flex-wrap gap-x-5 gap-y-2 text-sm font-medium">{nav.map(n => <Link key={n.to} to={n.to} className="hover:text-brand">{n.label}</Link>)}</div></div><div className="mx-auto flex max-w-7xl flex-wrap justify-between gap-2 border-t border-border px-5 py-5 text-xs text-muted-foreground sm:px-8"><span>© {new Date().getFullYear()} FRONTDESK. Early access in the UK.</span><Link to="/login" className="hover:text-foreground">Owner login</Link></div></footer></div>;
}
export function Meta({ eyebrow, title, children }: { eyebrow: string; title: string; children?: ReactNode }) { return <div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.14em] text-brand">{eyebrow}</p><h2 className="mt-4 text-3xl font-bold leading-tight sm:text-4xl">{title}</h2>{children && <p className="mt-5 text-base leading-relaxed text-muted-foreground">{children}</p>}</div>; }
export function Action({ to, children, secondary = false }: { to: "/demo" | "/how-it-works" | "/pricing" | "/dental" | "/trades"; children: ReactNode; secondary?: boolean }) { return <Button asChild variant={secondary ? "outline" : "default"} size="lg" className="w-full sm:w-auto"><Link to={to}>{children}{!secondary && <ArrowUpRight />}</Link></Button>; }
export function LeadPreview() { return <div className="w-full max-w-md border border-border bg-card p-6 shadow-xl shadow-primary/10"><div className="flex items-center justify-between border-b border-border pb-4"><div><p className="text-xs font-bold uppercase tracking-[0.1em] text-brand">Illustrative lead</p><h3 className="mt-1 font-bold">New enquiry captured</h3></div><span className="bg-destructive/10 px-2 py-1 text-xs font-bold text-destructive">URGENT</span></div><dl className="mt-5 space-y-4 text-sm">{[["Caller", "Mrs D. Whitfield"], ["Phone", "07••• ••• 214"], ["Postcode", "LS15 8••"], ["Issue", "Boiler leaking; no hot water"], ["Next step", "Priority callback requested"]].map(([k,v]) => <div key={k} className="grid grid-cols-[90px_1fr] gap-3"><dt className="text-muted-foreground">{k}</dt><dd className="font-semibold">{v}</dd></div>)}</dl><p className="mt-6 border-t border-border pt-4 text-xs text-muted-foreground">Fictional example — not a real customer record.</p></div>; }
export function RequestSection({ title, source, kind = "pilot", buttonText }: { title: string; source: "home" | "dental" | "trades" | "demo"; kind?: "pilot" | "demo"; buttonText?: string }) { return <section className="border-t border-border bg-muted/40 py-16 sm:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 sm:px-8 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-brand">Get started</p><h2 className="mt-4 max-w-lg text-3xl font-bold leading-tight sm:text-4xl">{title}</h2><p className="mt-5 max-w-md leading-relaxed text-muted-foreground">Tell us about your business. We'll be in touch to discuss the right setup for your calls.</p></div><div className="max-w-2xl"><PilotFormBridge source={source} kind={kind} buttonText={buttonText}/></div></div></section>; }
import { PilotForm as PilotFormBridge } from "@/components/PilotForm";
export function pageHead(title: string, description: string) { return { meta: [{ title }, { name: "description", content: description }, { property: "og:title", content: title }, { property: "og:description", content: description }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }; }